@startuml
class line {
    + xStart : int <<get>>
    + yStart : int <<get>>
    + xEnd : int <<get>>
    + yEnd : int <<get>>
    + styles : string <<get>>
    + line(xStart:int, yStart:int, xEnd:int, yEnd:int, styles:string)
    + <<override>> printshape() : string
}
shape <|-- line
@enduml
