@startuml
class polyline {
    + points : string <<get>>
    + styles : string <<get>>
    + polyline(points:string, styles:string)
    + <<override>> printshape() : string
}
shape <|-- polyline
@enduml
