@startuml
class AddShapeCommand {
    + AddShapeCommand(s:shape, c:Canvas)
    + <<override>> Do() : void
    + <<override>> Undo() : void
}
Command <|-- AddShapeCommand
AddShapeCommand --> "shape" shape
AddShapeCommand --> "canvas" Canvas
@enduml
